DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS USER_ROLES;

CREATE TABLE ROLE (ID SERIAL PRIMARY KEY, DESCRIPTION VARCHAR(255), NAME VARCHAR(255));
CREATE TABLE USER (ID SERIAL PRIMARY KEY, AGE INTEGER, PASSWORD VARCHAR(255), SALARY BIGINT, USERNAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE USER_ROLES (ID SERIAL, ROLE_ID BIGINT NOT NULL, USER_ID BIGINT NOT NULL, PRIMARY KEY (USER_ID, ROLE_ID));
