DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USER_ROLES;

CREATE TABLE ROLE (ID SERIAL PRIMARY KEY, DESCRIPTION VARCHAR(255) NULL, NAME VARCHAR(255));
CREATE TABLE USERS (ID SERIAL PRIMARY KEY, FIRST_NAME VARCHAR(255) NOT NULL, LAST_NAME VARCHAR(255) NOT NULL, AGE INTEGER NULL, USERNAME VARCHAR(255), PASSWORD VARCHAR(255), SALARY BIGINT NULL);
CREATE TABLE USER_ROLES (ID SERIAL, ROLE_ID BIGINT NOT NULL, USER_ID BIGINT NOT NULL, PRIMARY KEY (USER_ID, ROLE_ID));
